# Site settings
title: Lovely, Lovely Synthesis~
# email: your-email@domain.com
description: "We like to have fun here. Music is fun."
baseurl: ""
url: "http://www.synth.love"
# twitter_username: jekyllrb
github_username:  jordanhalase

# Build settings
markdown: kramdown
permalink: pretty
