# Site settings
title: Lovely, Lovely Synthesizers~
# email: your-email@domain.com
description: "We love synthesizers, and we love freedom. Here's some free and open source music synthesis stuff written in the open LV2 standard."
baseurl: ""
url: "http://www.synth.love"
# twitter_username: jekyllrb
github_username:  jordanhalase

# Build settings
markdown: kramdown
permalink: pretty
