# Site settings
title: Synthesizers by Jordan and Friends
# email: your-email@domain.com
description: "We love synthesizers, and we love freedom. Here's some free and open source music synthesis stuff in the LV2 standard."
baseurl: ""
url: "http://www.synth.love"
# twitter_username: jekyllrb
github_username:  jordanhalase

# Build settings
markdown: kramdown
permalink: pretty
